# Generated by Django 3.1.3 on 2020-11-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201130_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='join_date',
        ),
    ]
