# Generated by Django 3.1.3 on 2020-12-02 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist_img', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=500)),
                ('livestream_link', models.URLField()),
            ],
        ),
    ]
