# Generated by Django 3.1.3 on 2020-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201203_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='recources_link',
            new_name='recource_link',
        ),
    ]
