# Generated by Django 3.1.3 on 2020-12-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20201203_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
