# Generated by Django 3.1.3 on 2020-12-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20201203_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default='Contact site administrator for contact information', max_length=200),
        ),
    ]
