# Generated by Django 3.1.3 on 2020-12-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_post_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
