# Generated by Django 3.1.3 on 2020-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20201203_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
